version: v1.0
steps:
  s1:
    displayName: "S1 Exec"
    command: cat
    arguments:
      - valueFrom: p2
    outputs:
      p3:
        dataName: dout

locations:
  l0:
    hostname: 127.0.0.1
    port: 8080
    workdir: .
  l1:
    hostname: 127.0.0.1
    port: 8081
    workdir: .
  l2:
    hostname: 127.0.0.1
    port: 8082
    workdir: .

choices:
  c1:
    condition: '"Hello" in open(p1).read()'

dependencies:
  d1:
    type: file
    value: "world.txt"
  d2:
    type: file
  dout:
    type: stdout
