version: v1.0
steps:
  s1:
    displayName: "StepA"
    command: cat
    arguments:
      - valueFrom: p1
  s2:
    displayName: "StepB"
    command: cat
    arguments:
      - valueFrom: p1

locations:
  l:
    hostname: 127.0.0.1
    port: 8080
    workdir: .

dependencies:
  d1:
    type: file
    value: "world.txt"
