version: v1.0
steps:
  s1:
    displayName: s1
    command: sh
    arguments:
      - valueFrom: p1
      - value: Hello
      - value: Ciao
    outputs:
      p2:
        dataName: d1
        glob: "Hello.txt"
      p3:
        dataName: d2
        glob: "Ciao.txt"
  s2:
    displayName: s2
    command: echo
    arguments:
      - valueFrom: p2
  s3:
    displayName: s3
    command: echo
    arguments:
      - valueFrom: p3


locations:
  ld:
    hostname: 127.0.0.1
    port: 8080
  l1:
    hostname: 127.0.0.1
    port: 8081
  l2:
    hostname: 127.0.0.1
    port: 8082
  l3:
    hostname: 127.0.0.1
    port: 8083


dependencies:
  d:
    type: file
    value: custom_cmd.sh
  d1:
    type: file
  d2:
    type: file
